# Generated by Django 4.0.5 on 2023-01-17 14:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contenu',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
