# Generated by Django 4.0.5 on 2023-01-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_articles_contenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contenu',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
